### ISSUE TITLE
It doesn't seem to be working.

### ISSUE THREAD

**Issue by SeongGyu1216** [Legend-Master/discord-better-image-viewer#4]
I activated it, but it doesn't change when I press the image!
Can you please update me?

**Comment by Legend-Master** [comment]
Did you download it from here (GitHub) or from Better Discord's plugin page?

If you are using the version from Better Discord's plugin page, that one is not updated yet, still waiting on approval (they don't have enough people reviewing them so it can be slow)

**Comment by SeongGyu1216** [comment]
I downloaded it from Better discord - Plugin Repo! I'll try downloading it from Github!

**Comment by SeongGyu1216** [comment]
Downloading from Github works fine! Thank you. I thought the update was the same. Your Plugin is so grateful to me. Thank you.

**Comment by SeongGyu1216** [comment]
I think it's good to close this topic

**Comment by Legend-Master** [comment]
Glad you enjoyed it 😀
