### ISSUE TITLE
plugin stretching images 

### ISSUE THREAD

**Issue by TheGreatTaz** [Legend-Master/discord-better-image-viewer#6]
the plugin has started stretching images instead of displaying them normally
![image](https://github.com/user-attachments/assets/cfce82e6-4b8f-470e-accc-7f6db247d091)
![image](https://github.com/user-attachments/assets/85dd5e26-8706-4e30-807d-fe80a96233de)
![image](https://github.com/user-attachments/assets/079f49ae-4267-403c-89f8-eb98d0189711)

**Comment by Legend-Master** [comment]
I just fixed this in 95f8d93ac7bdd4753ab673afed2f4aacad5ae3b2 but I don't have the time to also fix it for the gallery view yet, I'll take a look when I got time

**Comment by jonesy-b-dev** [comment]
I updated the plugin today and its not fixed for me, I'm on version v1.4, is this the fixed version?

**Comment by Legend-Master** [comment]
You can try downloading it from [github](https://raw.githubusercontent.com/Legend-Master/discord-better-image-viewer/refs/heads/main/BetterImageViewer.plugin.js) for now, I want to also get the gallery fixed before publishing a new version

**Comment by jonesy-b-dev** [comment]
alright thanks!

**Comment by Legend-Master** [comment]
The one on better discord site is on the fixed version now as well, closing this as complete, thanks for the report!

Also the gallery view should also be fixed on the github version as well
