### ISSUE TITLE
Issue with scaling

### ISSUE THREAD

**Issue by FireBoy00** [Legend-Master/discord-better-image-viewer#8]
The image is scaled/stretched in width. Instead it should be normal Discord image viewing, but with support for zooming and moving the pic arround.
![image](https://github.com/user-attachments/assets/787d5624-2aba-46f1-88a9-b28bc1f9de5c)

**Comment by ryan8374** [comment]
This appears to have been corrected with version 1.5.

**Comment by Legend-Master** [comment]
Yes, please see #6
